name: Proselint Grammar Check for Modified .mdx Files

on:
  pull_request:
    paths:
      - '**/*.mdx'  # Target all .mdx files in the repository

jobs:
  proselint:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2  # Ensure enough history is fetched for comparison

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # Specify the required Python version

      # Step 3: Install Proselint
      - name: Install Proselint
        run: |
          python -m pip install --upgrade pip
          pip install proselint

      # Step 4: Identify Modified .mdx Files
      - name: Identify Modified .mdx Files
        id: find_files
        run: |
          git diff --name-only --diff-filter=AM origin/${{ github.base_ref }}...${{ github.head_ref }} -- '*.mdx' > modified_files.txt
          if [ -s modified_files.txt ]; then
            echo "Modified .mdx files detected:"
            cat modified_files.txt
            echo "files=$(cat modified_files.txt | paste -sd ' ' -)" >> $GITHUB_OUTPUT
          else
            echo "No modified .mdx files detected."
            echo "files=" >> $GITHUB_OUTPUT
          fi

      # Step 5: Run Proselint on Modified .mdx Files
      - name: Run Proselint
        if: steps.find_files.outputs.files != ''
        run: |
          for file in ${{ steps.find_files.outputs.files }}; do
            echo "Linting $file"
            proselint "$file"
          done
